version: '3.8'

services:
  # Development server (uses pre-built local guest binaries)
  # Optimized with dependency caching and BuildKit cache mounts
  api-server-dev:
    build:
      context: ..
      dockerfile: api-server/Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - RISC0_DEV_MODE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    profiles:
      - dev

  # Production server (x86_64 with full RISC Zero toolchain)
  api-server-prod:
    build:
      context: ..
      dockerfile: api-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    profiles:
      - prod
